### ISSUE TITLE
MakeFile

### ISSUE THREAD

**Issue by Cantalbyte** [JakeDahl/ExternalDayZ#1]
Can or will you make a make file so I can compile, because gcc comes back with many errors.

**Comment by Cantalbyte** [comment]
@JakeDahl

**Comment by JakeDahl** [comment]
You'll need to implement your own driver routines to build it.

**Comment by Cantalbyte** [comment]
Which Drivers?
@JakeDahl

**Comment by Cantalbyte** [comment]
Is there anyway to contact you quicker Jake?

**Comment by JakeDahl** [comment]
The driver I'm referring to is one you build yourself for reading and writing memory from the kernel. This is the core piece which is needed for this to function, as this program relies on it and it also circumvents the anti cheats basic protection. You would implement your driver's read and write functions into this project to get it working.

To get started I would do a quick search on Google for resources. This project is no longer updated and I'm out of the dayz scene so I cannot really provide support on updating it anymore. I'm familiar with the games engine overall but not with any updates to it since posting this source.

**Comment by Cantalbyte** [comment]
Ok thanks for the info.
